name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ext: so
          - os: macos-latest
            ext: dylib
          - os: windows-latest
            ext: dll
    steps:
      - uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"

      - name: Build binaries
        run: |
          cd core
          cargo build --release

      - name: print info
        run: |
          tree core

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: sublime_fuzzy_dyn.${{ matrix.ext }}
          path: core/target/release/sublime_fuzzy_dyn.${{ matrix.ext }}
